dist: trusty
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - 1.8.7

env:
  - COVERAGE_TARGET_VERSION="2.7"

before_install:
  - dpkg --compare-versions $(ruby --version | grep -Eo "([0-9]\.)+[0-9]+") ge 2.3 && gem update --system --no-document && gem update --no-document || true
