require "bcdice/dice_table/chain_table"
require "bcdice/dice_table/d66_grid_table"
require "bcdice/dice_table/d66_range_table"
require "bcdice/dice_table/d66_table"
require "bcdice/dice_table/range_table"
require "bcdice/dice_table/sai_fic_skill_table"
require "bcdice/dice_table/table"
