#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.1
# from Racc grammar file "".
#

require 'racc/parser.rb'


require "bcdice/common_command/lexer"
require "bcdice/common_command/add_dice/node"

module BCDice
  module CommonCommand
    module AddDice
      class Parser < Racc::Parser


def self.parse(source)
  new.parse(source)
end

def parse(source)
  @lexer = Lexer.new(source)
  do_parse()
rescue ParseError
  nil
end

private

def next_token
  @lexer.next_token
end

# 加減算の右辺が負数である場合に加減算を逆転させる
def expand_negate(op, rhs)
  if rhs.is_a?(Node::Negate)
    if op == :+
      return [:-, rhs.body]
    elsif op == :-
      return [:+, rhs.body]
    end
  end

  [op, rhs]
end
##### State transition tables begin ###

racc_action_table = [
    13,    16,    17,    18,    19,    13,    32,    13,     3,     8,
     9,     4,    13,    12,    13,    26,     8,     9,    12,    13,
    12,     8,     9,     8,     9,    12,    13,    12,     8,     9,
    14,    13,    12,    13,    22,     8,     9,    13,    13,    12,
     8,     9,     8,     9,    12,    15,    12,     8,     9,   nil,
    12,    12,   nil,    16,    17,    16,    17,    18,    19,    18,
    19,    34,    35,    38,    37,    40,    41,    42,    43 ]

racc_action_check = [
    15,    23,    23,     6,     6,    22,    23,     2,     0,    15,
    15,     1,     8,    15,     9,    15,     2,     2,    22,    12,
     2,     8,     8,     9,     9,     8,    16,     9,    12,    12,
     4,    17,    12,    18,    11,    16,    16,    36,    19,    16,
    17,    17,    18,    18,    17,     5,    18,    19,    19,   nil,
    36,    19,   nil,     5,     5,    25,    25,    27,    27,    28,
    28,    30,    30,    31,    31,    37,    37,    38,    38 ]

racc_action_pointer = [
     4,    11,     5,   nil,    30,    42,   -10,   nil,    10,    12,
   nil,    29,    17,   nil,   nil,    -2,    24,    29,    31,    36,
   nil,   nil,     3,   -10,   nil,    44,   nil,    44,    46,   nil,
    52,    58,   nil,   nil,   nil,   nil,    35,    58,    60,   nil,
   nil,   nil,   nil,   nil ]

racc_action_default = [
    -3,   -28,   -28,    -4,   -28,    -1,    -9,   -12,   -28,   -28,
   -18,   -21,   -28,   -27,    44,   -28,   -28,   -28,   -28,   -28,
   -16,   -17,   -28,   -28,    -2,    -5,    -6,    -7,    -8,   -10,
   -13,   -19,   -26,   -11,   -14,   -15,   -28,   -28,   -28,   -20,
   -22,   -23,   -24,   -25 ]

racc_goto_table = [
    31,     1,     5,    27,    28,     2,    20,    21,    24,    33,
    36,   nil,    23,   nil,    39,    25,    29,    30 ]

racc_goto_check = [
     9,     1,     3,     5,     5,     2,     6,     6,     4,     7,
    10,   nil,     3,   nil,     9,     3,     6,     6 ]

racc_goto_pointer = [
   nil,     1,     5,     0,    -7,   -13,    -2,   -21,   nil,   -22,
   -21 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     6,     7,   nil,    10,    11,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 19, :_reduce_1,
  4, 19, :_reduce_2,
  0, 20, :_reduce_3,
  1, 20, :_reduce_4,
  1, 22, :_reduce_none,
  1, 22, :_reduce_6,
  3, 21, :_reduce_7,
  3, 21, :_reduce_8,
  1, 21, :_reduce_none,
  3, 23, :_reduce_10,
  4, 23, :_reduce_11,
  1, 23, :_reduce_none,
  0, 25, :_reduce_13,
  1, 25, :_reduce_14,
  1, 25, :_reduce_15,
  2, 24, :_reduce_16,
  2, 24, :_reduce_17,
  1, 24, :_reduce_none,
  3, 26, :_reduce_19,
  5, 26, :_reduce_20,
  1, 26, :_reduce_none,
  2, 28, :_reduce_22,
  2, 28, :_reduce_23,
  2, 28, :_reduce_24,
  2, 28, :_reduce_25,
  3, 27, :_reduce_26,
  1, 27, :_reduce_27 ]

racc_reduce_n = 28

racc_shift_n = 44

racc_token_table = {
  false => 0,
  :error => 1,
  :NUMBER => 2,
  :CMP_OP => 3,
  :S => 4,
  :D => 5,
  :K => 6,
  :H => 7,
  :L => 8,
  :U => 9,
  :R => 10,
  :PLUS => 11,
  :MINUS => 12,
  :ASTERISK => 13,
  :SLASH => 14,
  :PARENL => 15,
  :PARENR => 16,
  :QUESTION => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NUMBER",
  "CMP_OP",
  "S",
  "D",
  "K",
  "H",
  "L",
  "U",
  "R",
  "PLUS",
  "MINUS",
  "ASTERISK",
  "SLASH",
  "PARENL",
  "PARENR",
  "QUESTION",
  "$start",
  "command",
  "secret",
  "add",
  "target",
  "mul",
  "unary",
  "round_type",
  "dice",
  "term",
  "filter_type" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
           secret, lhs = val
           raise ParseError unless lhs.include_dice?

           result = Node::Command.new(secret, lhs)

    result
end

def _reduce_2(val, _values, result)
           secret, lhs, cmp_op, rhs = val
           raise ParseError if !lhs.include_dice? || rhs.include_dice? || cmp_op.nil?

           result = Node::Command.new(secret, lhs, cmp_op, rhs)

    result
end

def _reduce_3(val, _values, result)
 result = false
    result
end

def _reduce_4(val, _values, result)
 result = true
    result
end

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = Node::UndecidedTarget.instance
    result
end

def _reduce_7(val, _values, result)
      lhs = val[0]
      op, rhs = expand_negate(:+, val[2])
      result = Node::BinaryOp.new(lhs, op, rhs)

    result
end

def _reduce_8(val, _values, result)
      lhs = val[0]
      op, rhs = expand_negate(:-, val[2])
      result = Node::BinaryOp.new(lhs, op, rhs)

    result
end

# reduce 9 omitted

def _reduce_10(val, _values, result)
      lhs = val[0]
      rhs = val[2]
      result = Node::BinaryOp.new(lhs, :*, rhs)

    result
end

def _reduce_11(val, _values, result)
       lhs = val[0]
       rhs = val[2]
       divied_class = val[3]
       result = divied_class.new(lhs, rhs)

    result
end

# reduce 12 omitted

def _reduce_13(val, _values, result)
 result = Node::DivideWithRoundingDown
    result
end

def _reduce_14(val, _values, result)
 result = Node::DivideWithRoundingUp
    result
end

def _reduce_15(val, _values, result)
 result = Node::DivideWithRoundingOff
    result
end

def _reduce_16(val, _values, result)
 result = val[1]
    result
end

def _reduce_17(val, _values, result)
         body = val[1]
         result = body.is_a?(Node::Negate) ? body.body : Node::Negate.new(body)

    result
end

# reduce 18 omitted

def _reduce_19(val, _values, result)
        times = val[0]
        sides = val[2]
        raise ParseError if times.include_dice? || sides.include_dice?

        result = Node::DiceRoll.new(times, sides)

    result
end

def _reduce_20(val, _values, result)
        times = val[0]
        sides = val[2]
        filter = val[3]
        n_filtering = val[4]
        raise ParseError if times.include_dice? || sides.include_dice? || n_filtering.include_dice?

        result = Node::DiceRollWithFilter.new(times, sides, n_filtering, filter)

    result
end

# reduce 21 omitted

def _reduce_22(val, _values, result)
 result = Node::DiceRollWithFilter::KEEP_HIGHEST
    result
end

def _reduce_23(val, _values, result)
 result = Node::DiceRollWithFilter::KEEP_LOWEST
    result
end

def _reduce_24(val, _values, result)
 result = Node::DiceRollWithFilter::DROP_HIGHEST
    result
end

def _reduce_25(val, _values, result)
 result = Node::DiceRollWithFilter::DROP_LOWEST
    result
end

def _reduce_26(val, _values, result)
 result = Node::Parenthesis.new(val[1])
    result
end

def _reduce_27(val, _values, result)
 result = Node::Number.new(val[0])
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

      end   # class Parser
    end   # module AddDice
  end   # module CommonCommand
end   # module BCDice
