# -*- coding: utf-8 -*-

require "rake/testtask"

task :default => :test

desc 'Clean coverage resuts'
task :clean_coverage do
  if RUBY_VERSION > '1.8.x'
    require 'simplecov'
    resultset_path = SimpleCov::ResultMerger.resultset_path
    FileUtils.rm resultset_path if File.exist? resultset_path
  end
end

namespace :test do
  Rake::TestTask.new(:dicebots) do |t|
    t.description = 'ダイスボット'

    t.test_files = ['test/testDiceBots.rb']
    t.libs = [
      'test',
      '.',
      'irc'
    ]

    unless RUBY_VERSION < '1.9'
      t.ruby_opts = [
        '--enable-frozen-string-literal'
      ]
    end
  end

  Rake::TestTask.new(:dicebot_loaders) do |t|
    t.description = 'ダイスボット読み込み'
    t.test_files = ['test/testDiceBotLoaders.rb']
  end

  Rake::TestTask.new(:dicebot_prefixes_compatibility) do |t|
    t.description = 'ダイスボットの接頭辞設定の後方互換性'
    t.test_files = ['test/testDiceBotPrefixesCompatibility.rb']
  end
end

task :test => [
  :clean_coverage,
  'test:dicebots',
  'test:dicebot_loaders',
  'test:dicebot_prefixes_compatibility'
]

if RUBY_VERSION >= '2.3'
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new
  task :test => [:rubocop]
end
